language: python
python:
  - "2.7"
env:
  - LOG=debug

before_install:
  - sudo apt-get -y install python-pip python-dev g++ make gfortran
install:
  - pip install --quiet --upgrade --use-mirrors numpy
  - pip install --use-mirrors --upgrade -r dev-requirements.txt
  - sudo python setup.py install

before_script:
  - pep8 --ignore E265 intuition tests
script:
  - nosetests -w tests --with-coverage --cover-package=intuition

branches:
  only:
    - master
    - develop
