language: python
python:
  - "2.7"
install:
  - sudo apt-get -y install python-pip python-dev g++ make gfortran mysql-client libmysqlclient-dev
  - pip install --upgrade -r scripts/installation/requirements.txt
script:
    - nosetests tests
