language: python
python:
  - "2.7"

before_install:
  - sudo apt-get -y install python-pip python-dev g++ make gfortran
install:
  - pip install --upgrade --use-mirrors numpy nosetests flake8 coveralls
  - pip install --upgrade --use-mirrors -r requirements.txt

before_script:
  - "flake8 zipline tests"
script:
  - nosetests -w tests

after_success:
  - coverage run --source=intuition setup.py nosetests
    #- nosetests -w tests --with-coverage --cover-package=tests
  - coveralls

branches:
  only:
    - master
    - develop
