---
#universe: EUR/USD,EUR/GBP,GBP/USD,USD/CHF,EUR/JPY,EUR/CHF,USD/CAD,AUD/USD,GBP/JPY
universe: cac40
end: 17h
frequency: 1min
modules:
  context: file
  manager: OptimalFrontier
  algorithm: StochasticGradientDescent
  data: EquitiesLiveSource

algorithm:
  save: true
  rebalance_period: 15
  refresh_period: 10
  window_length: 60
  stddev_window: 9
  vwap_window: 5
  long_window : 25
  short_window : 5
  threshold : 0
  ignored: [volume pouet]
  gradient_iterations: 5
  signal_frontier: 0.5
  decision_frontier: 0.5

manager:
  cash: 10000
  load_backup: false
  connected: false
  android: false
  loopback: 60
  source: mysql
  perc_sell: 1.0
  max_weight: 0.3
  sell_scale: 100
  buy_scale: 150
